/** Shared tag names for BD Blood server reads and mutation invalidation. */
export const CACHE_TAGS = {
  POSTS: "posts",
  POST: (slugOrId: string) => `post-${slugOrId}`,
  BLOGS: "blogs",
  BLOG: (slug: string) => `blog-${slug}`,
  GALLERY: "gallery",
  GALLERY_ITEM: (slug: string) => `gallery-${slug}`,
  ORGANIZATIONS: "organizations",
  ORGANIZATION: (slugOrId: string) => `organization-${slugOrId}`,
  POLICIES: "policies",
  FAQS: "faqs",
  MEDICAL_INSTITUTIONS: "medical-institutions",
  MEDICAL_INSTITUTION: (slugOrId: string) => `medical-${slugOrId}`,
  DOCTORS: "doctors",
  MEDICAL_INFOS: "medical-informations",
  MEDICAL_ADS: "medical-advertisements",
  ANALYTICS: "analytics",
  BLOOD_REQUESTS: "blood-requests",
  DONORS_PUBLIC: "donors-public",
  EVENTS: "events",
  LOCATION: "location",
  BLOOD_GROUPS: "blood-groups",
  USER_ME: "user-me",
  REPORTS: "reports",
} as const;
